import type { Job } from '../types/JobType';

export let mockJobsData: { data: Job[] } = {
  data: [
    {
      id: 1,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 1,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 2,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 3,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 4,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 5,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 6,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 7,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 8,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 9,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 10,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 11,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 12,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 13,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 14,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 15,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 6,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 7,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 1,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 2,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 3,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 4,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 5,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 6,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 7,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 8,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 9,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 10,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 11,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 12,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 13,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 14,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 15,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 6,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 7,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 1,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 2,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 3,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 4,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 5,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 6,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 7,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 8,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 9,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 10,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 11,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 12,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 13,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 14,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 15,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 6,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 7,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 1,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 2,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 3,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 4,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 5,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 6,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 7,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 8,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 9,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 10,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 11,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 12,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 13,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 14,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 15,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 6,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 7,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 2,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 3,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 4,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 5,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 6,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 7,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 8,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 9,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 10,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 11,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 12,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 13,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 14,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 15,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 6,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 7,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 1,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 2,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 3,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 4,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 5,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 6,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 7,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 8,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'applied',
      createdAt: '2024-07-03',
    },
    {
      id: 9,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 10,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 11,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 12,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 13,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 14,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
    {
      id: 15,
      position: 'Frontend Developer',
      company: 'TechCorp',
      status: 'applied',
      createdAt: '2024-07-01',
    },
    {
      id: 6,
      position: 'UI/UX Designer',
      company: 'Designify',
      status: 'interview',
      createdAt: '2024-07-03',
    },
    {
      id: 7,
      position: 'Backend Developer',
      company: 'CodeBase',
      status: 'rejected',
      createdAt: '2024-07-05',
    },
  ],
};

export function addMockJob(job: Job) {
  mockJobsData = {
    data: [...mockJobsData.data, job],
  };
}

export function deleteMockJob(id: number) {
  mockJobsData = {
    data: mockJobsData.data.filter((job) => job.id !== id),
  };
}

export function updateMockJob(id: number, data: Partial<Job>) {
  mockJobsData = {
    data: mockJobsData.data.map((job) => (job.id !== id ? job : { ...job, ...data })),
  };
}
